name: 'build apk'
description: 'Builds apk and returns path as output'
inputs:
  flavour: # id of input
    description: 'Pass the flavour you want to build artefacts for'
    required: false
    default: 'release'
outputs:
  apk-path:
    description: "Path to APK"
    value: ${{ steps.build-apk.outputs.apk-path }}
  apk-directory:
    description: "Directory containing APK"
    value: ${{ steps.build-apk.outputs.apk-directory }}
runs:
  using: "composite"
  steps:
    - name: Pre-build patches
      shell: bash
      run: |
        echo "Applying runtime patches..."
        # Patch Folly headers in gradle cache if they exist
        find ~/.gradle/caches -path "*/F14Table.h" -type f 2>/dev/null | head -10 | while read -r file; do
          echo "Patching: $file"
          sed -i 's/static_assert(std::regular<F14HashToken>);/\/\/ static_assert removed for C++17/' "$file" 2>/dev/null || true
        done
        
        # Run common fixes if script exists
        if [ -f "scripts/fix-common-android-errors.sh" ]; then
          ./scripts/fix-common-android-errors.sh
        fi
        
    - name: Build APK
      id: build-apk
      shell: bash
      env:
        INPUT_FLAVOUR: ${{ inputs.flavour }}
      run: |
        # Build from android directory
        echo "Starting Android build..."
        BUILD_STATUS=0
        
        cd android
        
        # Clean before build
        if [ -f "pre-build-cleanup.sh" ]; then
          ./pre-build-cleanup.sh
        fi
        
        # Use Java directly to run gradle wrapper to avoid path issues
        java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain assembleRelease --no-daemon 2>&1 | \
          tee ../build.log | \
          grep -E "(FAILED|ERROR|BUILD|Task|success)" | \
          tail -200 || BUILD_STATUS=$?
        cd ..
        
        # Check build status
        if [ $BUILD_STATUS -ne 0 ]; then
          echo "=== Last 300 lines of build output ==="
          tail -300 build.log 2>/dev/null || tail -300 build-gradle.log 2>/dev/null
          echo "Build failed! Running Metro bundler test..."
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output /tmp/test.bundle --assets-dest /tmp 2>&1 | tail -100
          exit 1
        fi
        
        # Find the APK
        APK_PATH="android/app/build/outputs/apk/release/app-release-unsigned.apk"
        APK_DIR="android/app/build/outputs/apk/release"
        echo "apk-path=$(echo $APK_PATH)" >> $GITHUB_OUTPUT
        echo "apk-directory=$(echo $APK_DIR)" >> $GITHUB_OUTPUT
        
        # Check if APK was actually created
        if [ -f "$APK_PATH" ]; then
          echo "✅ BUILD SUCCESS! APK created at: $APK_PATH"
          ls -lh "$APK_PATH"
        else
          echo "❌ BUILD FAILED! APK not found at: $APK_PATH"
          exit 1
        fi