name: 'Build apk'
description: 'Builds apk and returns path as output'
inputs:
  flavour: # id of input
    description: 'Pass the flavour you want to build artefacts for'
    required: false
    default: 'release'
outputs:
  apk-path:
    description: "Path to APK"
    value: ${{ steps.build-apk.outputs.apk-path }}
  apk-directory:
    description: "Directory containing APK"
    value: ${{ steps.build-apk.outputs.apk-directory }}
runs:
  using: "composite"
  steps:
    - name: Build APK
      id: build-apk
      shell: bash
      env:
        INPUT_FLAVOUR: ${{ inputs.flavour }}
      run: |
        # Build from android directory (renamed from GreedGross)
        echo "Starting Android build..."
        BUILD_STATUS=0
        
        cd android
        ./gradlew assembleRelease --no-daemon 2>&1 | \
          tee ../build.log | \
          grep -E "(FAILED|ERROR|BUILD|Task|success)" | \
          tail -200 || BUILD_STATUS=$?
        cd ..
        
        # Check build status
        if [ $BUILD_STATUS -ne 0 ]; then
          echo "=== Last 300 lines of build output ==="
          tail -300 build.log 2>/dev/null || tail -300 build-gradle.log 2>/dev/null
          echo "Build failed! Running Metro bundler test..."
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output /tmp/test.bundle --assets-dest /tmp 2>&1 | tail -100
          exit 1
        fi
        
        # Find the APK
        PATH="android/app/build/outputs/apk/release/app-release-unsigned.apk"
        DIR="android/app/build/outputs/apk/release"
        echo "apk-path=$(echo $PATH)" >> $GITHUB_OUTPUT
        echo "apk-directory=$(echo $DIR)" >> $GITHUB_OUTPUT
        
        # Check if APK was actually created
        if [ -f "$PATH" ]; then
          echo "✅ BUILD SUCCESS! APK created at: $PATH"
          ls -lh "$PATH"
        else
          echo "❌ BUILD FAILED! APK not found at: $PATH"
          exit 1
        fi