name: Build Simple

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - run: npm install --legacy-peer-deps
      
      - name: Build
        run: |
          cd GreedGross
          chmod +x gradlew
          ./gradlew --version
          ./gradlew tasks