name: simple build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          
      - run: npm install --legacy-peer-deps
      
      # Fix namespace issues
      - run: |
          chmod +x fix-namespaces.sh
          ./fix-namespaces.sh
      
      # Fix Gradle configuration issues
      - run: |
          chmod +x fix-gradle-configs.sh
          ./fix-gradle-configs.sh
      
      # Fix missing default configurations
      - name: Fix missing configurations
        run: |
          echo "Fixing missing default configurations..."
          MODULES=(
            "react-native-device-info"
            "@react-native-firebase/auth"
            "@react-native-firebase/app"
            "@react-native-firebase/firestore"
            "@react-native-firebase/storage"
          )
          
          for module in "${MODULES[@]}"; do
            MODULE_PATH=$(echo "$module" | sed 's/@//')
            BUILD_FILE="node_modules/$MODULE_PATH/android/build.gradle"
            if [ -f "$BUILD_FILE" ]; then
              if ! grep -q "configurations {" "$BUILD_FILE"; then
                echo "" >> "$BUILD_FILE"
                echo "configurations { default }" >> "$BUILD_FILE"
              fi
            fi
          done
      
      # Dai permessi di esecuzione a gradlew (se necessario)
      - run: chmod +x android/gradlew
      
      # Esegui il build con gradlew
      - run: cd android && ./gradlew bundleRelease --stacktrace
