name: simple build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          
      - run: npm install --legacy-peer-deps
      
      - name: Fix Firebase modules
        run: |
          echo "Removing publishing blocks from Firebase modules..."
          for firebase_module in auth app firestore storage analytics; do
            BUILD_FILE="node_modules/@react-native-firebase/$firebase_module/android/build.gradle"
            if [ -f "$BUILD_FILE" ]; then
              echo "Fixing @react-native-firebase/$firebase_module..."
              # Comment out the problematic afterEvaluate { publishing { ... } } block
              sed -i '/afterEvaluate {/,/^}/s/^/\/\/ /' "$BUILD_FILE" || true
            fi
          done
          
      - name: Fix react-native-safe-area-context
        run: |
          if [ -f "fix-safe-area-context.sh" ]; then
            chmod +x fix-safe-area-context.sh
            ./fix-safe-area-context.sh
          fi
      
      - run: |
          chmod +x fix-namespaces.sh
          ./fix-namespaces.sh
      
      - name: Fix missing configurations
        run: |
          echo "Fixing missing default configurations..."
          MODULES=(
            "@react-native-firebase/auth"
            "@react-native-firebase/app"
            "@react-native-firebase/firestore"
            "@react-native-firebase/storage"
          )
          
          for module in "${MODULES[@]}"; do
            MODULE_PATH=$(echo "$module" | sed 's/@//')
            BUILD_FILE="node_modules/$MODULE_PATH/android/build.gradle"
            if [ -f "$BUILD_FILE" ]; then
              if ! grep -q "configurations {" "$BUILD_FILE"; then
                echo "" >> "$BUILD_FILE"
                echo "configurations { default }" >> "$BUILD_FILE"
              fi
            fi
          done
      
      - name: Setup Gradle Properties
        run: |
          mkdir -p android
          cat > android/gradle.properties << EOF
          org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
          org.gradle.parallel=false
          org.gradle.configureondemand=false
          org.gradle.daemon=false
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.jvm.target.validation.mode=IGNORE
          org.gradle.warning.mode=none
          android.suppressUnsupportedCompileSdk=35
          EOF
          
      - name: Setup Android SDK
        run: |

          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "Android SDK location: $ANDROID_SDK_ROOT"
      
      - run: chmod +x android/gradlew
      
      - name: Clean Bouncy Castle cache
        run: |
          rm -rf ~/.gradle/caches/modules-2/files-2.1/org.bouncycastle/
          rm -rf ~/.gradle/caches/jars-9/
      
      - name: Build with 5 attempts
        run: |
          cd android
          
          for attempt in 1 2 3 4 5; do
            echo "::group::Build Attempt $attempt/5"
            
            if ./gradlew bundleRelease --stacktrace --no-daemon; then
              
              echo "::endgroup::"
              exit 0
            else
              echo "::endgroup::"
            fi
            
            if [ $attempt -eq 5 ]; then
              exit 1
            fi
            
            echo "::group::Fixing errors for attempt $((attempt + 1))"
            
            if [ $attempt -eq 1 ]; then
              echo "Cleaning all caches..."
              rm -rf ~/.gradle/caches/
              ./gradlew --stop || true
              
            elif [ $attempt -eq 2 ]; then
              echo "Downgrading problematic dependencies..."
              echo "" >> build.gradle
              echo "allprojects {" >> build.gradle
              echo "    configurations.all {" >> build.gradle
              echo "        resolutionStrategy {" >> build.gradle
              echo "            force 'org.bouncycastle:bcprov-jdk18on:1.77'" >> build.gradle
              echo "        }" >> build.gradle
              echo "    }" >> build.gradle
              echo "}" >> build.gradle
              
            elif [ $attempt -eq 3 ]; then
              echo "Increasing memory and cleaning..."
              sed -i 's/-Xmx4096m/-Xmx6144m/g' gradle.properties
              ./gradlew clean
              rm -rf build/ app/build/
              
              echo "Fixing specific module configurations..."
              cd ..
              
              echo "Removing publishing blocks from Firebase modules..."
              for firebase_module in auth app firestore storage analytics; do
                BUILD_FILE="node_modules/@react-native-firebase/$firebase_module/android/build.gradle"
                if [ -f "$BUILD_FILE" ]; then
                  echo "Fixing @react-native-firebase/$firebase_module..."
                  # Comment out the problematic afterEvaluate { publishing { ... } } block
                  sed -i '/afterEvaluate {/,/^}/s/^/\/\/ /' "$BUILD_FILE" || true
                fi
              done
              
              cd android
              
            elif [ $attempt -eq 4 ]; then
              echo "Nuclear reset..."
              cd ..
              rm -rf ~/.gradle
              rm -rf android/.gradle android/build android/app/build
              
              sed -i '/android {/a\    namespace "com.rnfs"' node_modules/react-native-fs/android/build.gradle 2>/dev/null || true
              sed -i '/android {/a\    namespace "com.swmansion.gesturehandler"' node_modules/react-native-gesture-handler/android/build.gradle 2>/dev/null || true
              sed -i '/android {/a\    namespace "com.BV.LinearGradient"' node_modules/react-native-linear-gradient/android/build.gradle 2>/dev/null || true
              sed -i '/android {/a\    namespace "io.invertase.firebase.auth"' node_modules/@react-native-firebase/auth/android/build.gradle 2>/dev/null || true
              
              cd android
            
            fi
            
            echo "::endgroup::"
            sleep 3
          done
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-build
          path: |
            android/app/build/outputs/bundle/release/*.aab
            android/app/build/outputs/apk/release/*.apk
