name: simple build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          
      - run: npm install --legacy-peer-deps
      
      # Dai permessi di esecuzione a gradlew (se necessario)
      - run: chmod +x ./gradlew
      
      # Esegui il build con gradlew
      - run: ./gradlew bundleRelease --stacktrace || true
