name: Usa Build APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - run: npm install --legacy-peer-deps
      
      - name: Setup Android
        run: |
          cd GreedGross
          chmod +x gradlew
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
      - name: Usa Build apk action
        uses: ./.github/actions/build-apk
        with:
          flavour: release